config/routes.rb
Rails.application.routes.draw do
  root to: 'hubs#index'
  resources :hubs
  resources :users

  # mms: I see users repeated many times.  Look into Member routes
  # mms: purpose of these routes is unclear.  How is 'users#sign_in' different from 'users#sign_in!'?  Our goal is to leave code better than we found it.
  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'

end

app/models/hub.rb
class Hub < ActiveRecord::Base
  # mms: no validations?
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_many :hubs
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  private
  def authenticate
    if !session[:user_id]
      # mms: recommend named route `sign_in_path`, over string
      redirect_to "/sign_in"
    end
  end

  # mms: do you see the benefit of this change?
  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  def index
    @hubs = current_user.hubs
  end

  def new
    @hub = Hub.new
  end

  def create
    # mms: inline this variable - no need for @user
    @user = current_user
    # mms: used local var - no view for :create
    @hub = @user.hubs.create!(hub_params)
    # mms: recommend using named route instead of string.
    redirect_to '/'
  end

  def show
    # mms: no @hub instantiation?  If you don't use :show, remove it.
  end

  def edit
    @hub = Hub.find(params[:id])
  end

  def update
    @hub = Hub.find(params[:id])
    # what happens if `hub.update` fails?  Either use if/then or raise the error.
    @hub.update(hub_params)

    redirect_to '/'
  end

  def destroy
    @hub = Hub.find(params[:id])
    @hub.destroy

    redirect_to '/'
  end

  private

  def hub_params
    params.require(:hub).permit(:acc_link, :photo_url, :title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate

  def index
    # mms: prefer getting random user from db, rather return all and then select one
    # mms: why @users (as instance var)?
    @users = User.all
    @randomUser = @users.sample
    redirect_to user_path(@randomUser)
  end

  def show
    @user = User.find(params[:id])
    @hubs = @user.hubs
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    # mms: reset session on every update?  Is there a specific change that requires this?
    reset_session
    redirect_to "/"
  end

  def destroy
    @user = current_user
    @user.destroy

    reset_session
    redirect_to "/"
  end

  def find
    @users = User.all
  end

  def sign_up
  end

  def sign_up!
    # mms: recommend changing the form so you can utilize user_params (string params here).
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      photo_url: params[:photo_url],
      email: params[:email],
      password_digest: BCrypt::Password.create(params[:password])
    )

    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end

    flash[:notice] = message
    redirect_to '/sign_in'
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(email: params[:email])

    # mms: recommend extracting a `authenticate` method.
    if !@user
      message = "This user doesn't exist!"
    elsif !BCrypt::Password.new( @user.password_digest ).is_password?(params[:password])
      message = "Your password's wrong!"
    else
      message = "You're signed in, #{@user.first_name}!"
      cookies[:email] = {
        value: @user.email,
        expires: 100.years.from_now
      }
      session[:user_id] = @user.id
    end
    flash[:notice] = message
    redirect_to "/"
  end

  def sign_out
    reset_session
    redirect_to "/"
  end

private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo_url, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hubs_helper.rb
module HubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hubs/edit.html.erb
<h3>Edit This Hub</h3>

<%= form_for @hub do |f| %>

<div class="aForm">

  <p>
    <%= f.label :acc_link %>
      <br>
    <%= f.text_field :acc_link %>
  </p>

  <p>
    <%= f.label :photo_url %>
      <br>
    <%= f.text_field :photo_url %>
  </p>

  <p>
    <%= f.label :title %>
      <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
      <br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>


<%= form_for @hub, method: :delete do |f| %>
  <%= f.submit value="Delete"%>
<% end %>

<% end %>
</div>

app/views/hubs/index.html.erb
<div class="dashboard">

  <div class="dHeading">
    <h1>Dashboard</h1>
  </div>

  <div class="dControls">
    <%= link_to "NEW HUB", new_hub_path %>
    <%= link_to "SETTINGS", edit_user_path(current_user)  %>
  </div>
</div>

<% @hubs.each do |hub| %>
    <div class="aHub">
        <h2>
          <a class="hub_link" href="<%= hub.acc_link %>" target="_blank">
            <%= hub.title %>
          </a>
        </h2>

        <p> <img class="hub_img" alt="" src="<%= hub.photo_url%>"/> </p>

        <p class="hub_info"> <%= hub.description %> </p>
        <p class='editHub'>
          <%= link_to 'Edit', edit_hub_path(hub) %>
        </p>
    </div>
  <% end %>

app/views/hubs/new.html.erb
<h2>New hub</h2>

<%= form_for @hub do |f| %>

<div class="aForm">

  <p>
    <%= f.label :acc_link %>
      <br>
    <%= f.text_field :acc_link %>
  </p>

  <p>
    <%= f.label :photo_url %>
      <br>
    <%= f.text_field :photo_url %>
  </p>

  <p>
    <%= f.label :title %>
      <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
      <br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Socialhub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800' rel='stylesheet' type='text/css'>
</head>

<body>


  <nav class="top_nav">

    <div class="nav-section">
      <p> <%= link_to 'Explore Random User', '/users' %> </p>
    </div>

    <div class="nav-section">
      <h1><%= link_to "SocialHub", '/' %></h1>
    </div>

    <div class="nav-section">
      <% if current_user %>
        <p>
         <img class="navImg" src="<%= current_user.photo_url %>">
          <%= link_to current_user.first_name, user_path(current_user) %>
        </p>
        <p> <a href="/sign_out">SIGN OUT</a> </p>
      <% else %>
        <p> <a href="/sign_up">SIGN UP</a> </p>
        <p> <a href="/sign_in">SIGN IN</a> </p>
      <% end %>
    </div>

  </nav>


  <div class="wrap">
    <%= flash[:notice] %>
    <%= yield %>
  </div>


</body>

</html>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<div class="aForm">

<p>
  <%= f.label :first_name %>
  <br>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %>
  <br>
  <%= f.text_field :last_name %>
</p>

<p>
  <%= f.label :photo_url %>
  <br>
  <%= f.text_field :photo_url %>
</p>

<p>
  <%= f.label :email %>
  <br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password %>
</p>

<p>
  <%= f.label :password_confirmation %>
  <br>
  <%= f.password_field :password_confirmation %>
</p>

<%= f.submit %>

<% end %>

<p>
<%= form_for @user, method: :delete do |f| %>
  <%= f.submit value="Delete"%>
<% end %>
</p>

</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
<ul>
  <li>
    <a href="/users/<%= user.id %>"><%= user.first_name%></a>
  </li>
</ul>
<% end %>

app/views/users/show.html.erb
<section class="user_profile">
    <p>
      <img class="profilePic" src="<%= @user.photo_url %>" alt="" />
    </p>
  <div class="profileName">
    <h2><%=@user.first_name%> <%= @user.last_name %></h2>
  </div>
</section>

<section class="user_hubs">
  <h2>Here Are <%= @user.first_name%>'s hubs </h2>

  <% @hubs.each do |hub| %>
    <div class="aHub">
      <h2>
        <a class="hub_link" href= "<%= hub.acc_link %>" target="_blank">
          <%= hub.title %>
        </a>
      </h2>
      <p> <img class="hub_img" src="<%= hub.photo_url%>" alt="" /> </p>
      <p class="hub_info"> <%= hub.description %> </p>
    </div>
  <% end %>

</section>

app/views/users/sign_in.html.erb
<h2>Sign in</h2>
<div class="aForm">
<%= form_for("/sign_in", method: "post") do %>
<p>
  <input type="text" name="email" placeholder="email" />
</p>
<p>
  <input type="password" name="password" placeholder="password" value="<%= cookies[:email] %>" />
</p>
  <input type="submit" value="Sign in" />
<% end %>
</div>

app/views/users/sign_up.html.erb
<h2>Sign up</h2>
<div class="aForm">
<!-- mms: recommend using `form_for` , to support strong params -->
<%= form_tag("/sign_up", method: "post") do %>
<p>
  <input type="text" name="first_name" placeholder="first name" />
</p>
<p>
  <input type="text" name="last_name" placeholder="last name" />
</p>
<p>
  <input type="text" name="photo_url" placeholder="photo_url">
</p>
<p>
  <input type="text" name="email" placeholder="email" />
</p>
<p>
  <input type="password" name="password" placeholder="password" />
</p>
<p>
  <input type="password" name="password_confirmation" placeholder="password again" />
</p>

<input type="submit" value="Create Account" />
<% end %>
</div>